name: head
on: 
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  pull_request:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: vars
        run: |
          echo "COMMIT_HASH=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - run: chmod +x gradlew
      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
      - run: ./gradlew build
        env:
          MOD_VERSION: git-${{ steps.vars.outputs.COMMIT_HASH }}
      - uses: actions/upload-artifact@v3
        with:
          name: slotlink ${{ steps.vars.outputs.COMMIT_HASH }}
          path: "./build/libs/**.jar"
